<?php
require_once 'db.php';
require_once 'security.php';
header('Content-Type: application/json');

// Increase limits for potentially large profile image payloads
ini_set('memory_limit', '128M');
set_time_limit(60);

$rawData = file_get_contents('php://input');

// Accept JSON POST payload
if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    echo json_encode(['success' => false, 'message' => 'Method Not Allowed']);
    exit;
}

// Use native security middleware to validate Bearer token
$userId = authenticate($pdo);
if (!$userId) {
    http_response_code(401);
    echo json_encode(['success' => false, 'message' => 'Unauthorized: Invalid token']);
    exit;
}

$data = json_decode($rawData, true);

if (!$data) {
    echo json_encode(['success' => false, 'message' => 'Invalid JSON payload.']);
    exit;
}

try {
    // Collect specific fields that are allowed to be updated natively by user
    $updates = [];
    $params = [];

    if (isset($data['name'])) {
        $cleanName = sanitizeInput($data['name']);
        $updates[] = "name = ?";
        $params[] = $cleanName;
        
        $updates[] = "avatar_text = ?";
        $params[] = generateInitials($cleanName);
    }

    if (isset($data['email'])) {
        // Enforce basic validation check for email
        $email = sanitizeInput($data['email']);
        if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
            echo json_encode(['success' => false, 'message' => 'Invalid email format.']);
            exit;
        }
        $updates[] = "email = ?";
        $params[] = $email;
    }

    if (isset($data['phone'])) {
        $updates[] = "phone = ?";
        $params[] = sanitizeInput($data['phone']);
    }

    if (isset($data['address'])) {
        $updates[] = "address = ?";
        $params[] = sanitizeInput($data['address']);
    }

    if (isset($data['profileImage'])) {
        $updates[] = "profile_image = ?";
        $params[] = $data['profileImage']; // Assumes Base64 encoding generated by FileReader
    }

    // New Preferences
    if (isset($data['email_notif'])) {
        $updates[] = "email_notif = ?";
        $params[] = $data['email_notif'] ? 1 : 0;
    }

    if (isset($data['push_notif'])) {
        $updates[] = "push_notif = ?";
        $params[] = $data['push_notif'] ? 1 : 0;
    }

    if (isset($data['sms_tracking'])) {
        $updates[] = "sms_tracking = ?";
        $params[] = $data['sms_tracking'] ? 1 : 0;
    }

    if (isset($data['theme'])) {
        $updates[] = "theme = ?";
        $params[] = sanitizeInput($data['theme']);
    }

    if (empty($updates)) {
        echo json_encode(['success' => true, 'message' => 'No changes provided.']);
        exit;
    }

    // Bind User ID to END of query execution string
    $params[] = (int)$userId;

    $sql = "UPDATE users SET " . implode(", ", $updates) . " WHERE id = ?";
    $stmt = $pdo->prepare($sql);

    if ($stmt->execute($params)) {
        // Fetch updated user data to return
        $fetchStmt = $pdo->prepare("SELECT id, name, email, phone, address, level, level_name, avatar_text, profile_image, status, role, email_notif, push_notif, sms_tracking, theme FROM users WHERE id = ?");
        $fetchStmt->execute([(int)$userId]);
        $user = $fetchStmt->fetch(PDO::FETCH_ASSOC);

        if (!$user) {
            clearSession(); // Wipe the stale cookie
            http_response_code(404);
            echo json_encode(['success' => false, 'message' => 'User profile not found. Please log in again.']);
            exit;
        }

        echo json_encode([
            'success' => true,
            'message' => 'Profile updated successfully',
            'data' => [
                'user' => [
                    'id' => (int)$user['id'],
                    'name' => $user['name'],
                    'email' => $user['email'],
                    'phone' => $user['phone'] ?? '',
                    'address' => $user['address'] ?? '',
                    'level' => $user['level'] ?? 1,
                    'levelName' => $user['level_name'] ?? 'Starter',
                    'avatar' => $user['avatar_text'] ?? '',
                    'profileImage' => (strlen($user['profile_image'] ?? '') > 50000) ? null : ($user['profile_image'] ?? null),
                    'status' => $user['status'],
                    'role' => $user['role'],
                    'email_notif' => (bool)($user['email_notif'] ?? true),
                    'push_notif' => (bool)($user['push_notif'] ?? true),
                    'sms_tracking' => (bool)($user['sms_tracking'] ?? true),
                    'theme' => $user['theme'] ?? 'blue'
                ]
            ]
        ]);
    } else {
        http_response_code(500);
        echo json_encode(['success' => false, 'message' => 'Failed to apply profile updates.']);
    }
} catch (\Throwable $e) {
    http_response_code(500);
    echo json_encode([
        'success' => false, 
        'message' => 'System error during profile update.',
        'debug' => (isset($config['DEBUG_MODE']) && $config['DEBUG_MODE']) || (function_exists('isDebugEnabled') && isDebugEnabled()) ? $e->getMessage() : null
    ]);
}
