<?php
require_once 'db.php';
require_once 'security.php';
require_once 'cors_middleware.php';

// Accept JSON POST payload
if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    echo json_encode(['success' => false, 'message' => 'Method Not Allowed']);
    exit;
}

// Use native security middleware to validate Bearer token
$userId = authenticate();
if (!$userId) {
    http_response_code(401);
    echo json_encode(['success' => false, 'message' => 'Unauthorized: Invalid token']);
    exit;
}

$rawData = file_get_contents('php://input');
$data = json_decode($rawData, true);

if (!$data) {
    echo json_encode(['success' => false, 'message' => 'Invalid JSON payload.']);
    exit;
}

try {
    // Collect specific fields that are allowed to be updated natively by user
    $updates = [];
    $params = [];

    if (isset($data['name'])) {
        $updates[] = "name = ?";
        $params[] = sanitizeInput($data['name']);
    }

    if (isset($data['email'])) {
        // Enforce basic validation check for email
        $email = sanitizeInput($data['email']);
        if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
            echo json_encode(['success' => false, 'message' => 'Invalid email format.']);
            exit;
        }
        $updates[] = "email = ?";
        $params[] = $email;
    }

    if (isset($data['phone'])) {
        $updates[] = "phone = ?";
        $params[] = sanitizeInput($data['phone']);
    }

    if (isset($data['address'])) {
        $updates[] = "address = ?";
        $params[] = sanitizeInput($data['address']);
    }

    if (isset($data['profileImage'])) {
        $updates[] = "profile_image = ?";
        $params[] = $data['profileImage']; // Assumes Base64 encoding generated by FileReader
    }

    if (empty($updates)) {
        echo json_encode(['success' => true, 'message' => 'No changes provided.']);
        exit;
    }

    // Bind User ID to END of query execution string
    $params[] = (int)$userId;

    $sql = "UPDATE users SET " . implode(", ", $updates) . " WHERE id = ?";
    $stmt = $pdo->prepare($sql);

    if ($stmt->execute($params)) {
        echo json_encode(['success' => true, 'message' => 'Profile updated successfully']);
    } else {
        http_response_code(500);
        echo json_encode(['success' => false, 'message' => 'Failed to apply profile updates.']);
    }
} catch (PDOException $e) {
    error_log("Profile Update Error: " . $e->getMessage());
    http_response_code(500);
    echo json_encode(['success' => false, 'message' => 'Database error during profile update.']);
}
